name: Hello World

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
   # set this to your preferred AWS region, e.g. ca-central-1
  AWS_REGION: ca-central-1
  
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: display message
      run: |
        ls ${{ github.workspace }} -lR
        echo This demo file shows a 
        echo very basic and easy-to-understand workflow.
